version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: America/Edmonton
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
    - 5.1.2
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
    - 14.14.31
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: xo
    versions:
    - 0.36.1
    - 0.37.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
